### ISSUE TITLE
Question About Lustre Version 

### ISSUE THREAD

**Issue by shishuron** [INRIA/velus#1]
I am trying to use some Lustre v6 code, but it fails to compile.Could you please tell me which version of Lustre this compiler uses, and where I can find the documentation for this version of Lustre?

**Comment by tbrk** [comment]
Hello @shishuron, the syntax of the source language accepted by the Vélus compiler is presented in section 2.1 of Basile Pesin's PhD thesis: http://velus.inria.fr/phd-pesin/thesis.pdf.

Vélus cannot compile Lustre v6 code directly for two reasons: (a) syntactic differences (tedious but easy to overcome), (b) lacking features, notably, Vélus does not support `pre`, arrays, or side-effects.

Please feel free to contact me by [mail](mailto:timothy.bourke@inria.fr) if I can be of any help or if you need more information.
